### PR TITLE
Backport optimizations for graphql-core

### PR DESCRIPTION
**Pull request by snuderl**
Backports a performance optimization that was done in graphql-core repository https://github.com/graphql-python/graphql-core/commit/1062cbb6c8b96cfb6b9569fb74c26d861bdeddd4

TLDR: Avoid using Promise.all if there is we have a single promise only

Also changes how tests are run a bit so we can execute pytest-benchmark.

Before:
```
-------------------------------------------------------------------------------------------- benchmark: 2 tests -------------------------------------------------------------------------------------------
Name (time in us)                   Min                   Max                Mean             StdDev              Median                IQR            Outliers  OPS (Kops/s)            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_executes_simple_query      87.4170 (1.0)        146.4170 (1.0)       91.3595 (1.0)       4.9577 (1.0)       90.2500 (1.0)       1.8965 (1.0)         51;66       10.9458 (1.0)         776           1
test_execute_list_results      469.0420 (5.37)     1,369.2080 (9.35)     494.5048 (5.41)     53.0961 (10.71)    482.0000 (5.34)     15.7500 (8.30)        31;59        2.0222 (0.18)        550           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

After:
```
------------------------------------------------------------------------------------------ benchmark: 2 tests ------------------------------------------------------------------------------------------
Name (time in us)                   Min                 Max                Mean             StdDev              Median               IQR            Outliers  OPS (Kops/s)            Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_executes_simple_query      77.9170 (1.0)      176.9580 (1.0)       81.5066 (1.0)       4.9002 (1.0)       80.7500 (1.0)      1.8228 (1.0)         40;58       12.2689 (1.0)        1011           1
test_execute_list_results      440.3330 (5.65)     677.6670 (3.83)     453.9464 (5.57)     19.7447 (4.03)     449.1250 (5.56)     7.1147 (3.90)        46;85        2.2029 (0.18)        855           1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by snuderl** [comment]
@aminland @ericls

**Comment by ericls** [comment]
Thanks @snuderl, will take a look.

**Comment by tony** [comment]
@ericls Any opinion on this PR? 

@ericls Thank you for the project, first saw the package mentioned [here](https://github.com/graphql-python/graphene/issues/1391#issuecomment-1267357493)

@snuderl Thank you for the PR!

**Comment by ericls** [comment]
Sorry about the delay, taking a look now

**Comment by tony** [comment]
@ericls Thank you!

Fine to bump to [graphql-core-promise on PyPI](https://pypi.org/project/graphql-core-promise/3.2.3.post1/#history) to 3.2.3.post2?

**Comment by tony** [comment]
(Up to you depending on how you want to handle version schemes, any type of bump will do!)

**Comment by ericls** [comment]
yea, oops, forgot to publish to pypi for the new version will do it soon

**Pull request merged**
